# frozen_string_literal: true

# LogsController provides access to Agent execution logs and debugging information.
#
# This controller displays log entries generated by individual agents during their
# execution, providing developers and users with debugging and monitoring capabilities:
#
# * Agent-specific log viewing and filtering
# * Error message display and troubleshooting
# * Execution history and performance monitoring
# * Log level filtering and search capabilities
#
# All log access is scoped to the current user's agents to ensure proper
# access control and data privacy. Logs are essential for debugging agent
# behavior and monitoring system health.
class LogsController < ApplicationController

  before_action :load_agent

  def index
    @logs = @agent.logs.all
    render action: :index, layout: false
  end

  def clear
    @agent.delete_logs!
    index
  end

  protected

  def load_agent
    @agent = current_user.agents.find(params[:agent_id])
  end

end
